#!/bin/bash

current_dir=`pwd`
base_dir=`dirname $0`

function get_current_branch() {
	git branch | grep '*' | sed 's/^\* \([a-zA-Z0-9]*\)/\1/'
}

function print_usage() {
	echo "#    ge: Git Tool Kit"
	echo "#    Simplify commonly used Git commands with intelligent assumptions"
	echo "#"
	echo "#    Usage: ge <command> [arguments]"
	echo "#"
	echo "#    Available commands:"
	echo "#        branch"
	echo "#        current_branch"
	echo "#        ls"
	echo "#        review"
	echo "#        help"
	echo "#    "
	echo "#    Show help for a specific command:"
	echo "#    ge help <command>"
}

function print_help() {
	if [ -z "$1" ]; then
		print_usage
	elif [ "$1" = "current_branch" ]; then
		echo "ge current_branch: Displays the currently checked out branch."
	else
		$base_dir/ge-$1 --help
	fi
}

if [ -z "$1" ]
then
	print_usage
	exit 0
fi

case $1 in
	'branch')
		shift
		$base_dir/ge-branch $@
		;;
	'current_branch')
		get_current_branch
		;;
	'ls')
		shift
		$base_dir/ge-ls $@
		;;
	'review')
		shift
		$base_dir/ge-review $@
		;;
	'help')
		shift
		print_help "$1"
		;;
esac

exit 0
