#!/bin/bash

current_dir=`pwd`
base_dir=`dirname $0`

function get_current_branch() {
	git branch | grep '*' | awk '{print $2}'
}

function print_usage() {
	echo "#    ge: Git Extensions"
	echo "#    Simplify commonly used Git commands with intelligent assumptions"
	echo "#"
	echo "#    Usage: ge <command> [arguments]"
	echo "#"
	echo "#    Available commands:"
	echo "#        branch"
	echo "#        help"
	echo "#        ls"
	echo "#        review"
	echo "#        svn"
	echo "#    "
	echo "#    Show help for a specific command:"
	echo "#    ge help <command>"
}

function print_help() {
	if [ -z "$1" ]; then
		print_usage
	elif [ "$1" = "current_branch" ]; then
		echo "ge current_branch: Displays the currently checked out branch."
	elif [ -f "$base_dir/ge-$1" ]; then
		$base_dir/ge-$1 --help
	else
		print_usage
	fi
}

if [ -z "$1" ]
then
	print_usage
	exit 0
fi

case $1 in
	'branch')
		shift
		$base_dir/ge-branch $@
		;;
	'current_branch')
		get_current_branch
		;;
	'ls')
		shift
		$base_dir/ge-ls $@
		;;
	'review')
		shift
		$base_dir/ge-review $@
		;;
  'svn')
    shift
    $base_dir/ge-svn $@
    ;;
	'help')
		shift
		print_help "$1"
		;;
	*)
		shift
		print_help
		;;
esac

exit 0
