#!/bin/bash

branch_ref=""
remote_ref="origin"
show_commands=0

function echo_command() {
	if [ "1" = "$show_commands" ]; then
		echo "    Command: $1"
	fi
}

function create_remote_branch() {
	orig_branch=`ge current_branch`
	set_refs "$1" "$2"
	
	echo_command "git checkout -b $branch_ref"
	git checkout -b $branch_ref
	
	echo_command "git push $remote_ref $branch_ref"
	git push $remote_ref $branch_ref
	
	echo_command "git checkout $orig_branch"
	git checkout $orig_branch
	
	echo_command "git branch -D $branch_ref"
	git branch -D $branch_ref
	
	echo_command "git checkout -t $remote_ref/$branch_ref"
	git checkout -t $remote_ref/$branch_ref
}

function delete_remote_branch() {
	set_refs "$1" "$2"
	echo_command "git checkout master"
	git checkout master
	
	echo_command "git branch -D $branch_ref"
	git branch -D $branch_ref
	
	echo_command "git push $remote_ref :$branch_ref"
	git push $remote_ref :$branch_ref
}

function track_remote_branch() {
	set_refs "$1" "$2"
	echo_command "git checkout -t $remote_ref/$branch_ref"
	git checkout -t $remote_ref/$branch_ref
}

function set_refs() {
	if [ -z "$1" ]; then
		print_usage
	elif [ -z "$2" ]; then
		branch_ref="$1"
		remote_ref="origin"
	else
		branch_ref="$2"
		remote_ref="$1"
	fi
}

function print_usage() {
	echo "#    ge-branch"
	echo "#    Create, delete and track remote branches in Git."
	echo "#    "
	echo "#    ge branch <command> [options] <remote or branch name> [branch name]"
	echo "#    "
	echo "#    ge branch"
	echo "#    ge branch --help"
	echo "#        Display this help messsage"
	echo "#    "
	echo "#    ge branch create mybranch"
	echo "#        Create a new branch called mybranch on origin"
	echo "#    "
	echo "#    ge branch create myremote mybranch"
	echo "#        Create a new branch on the remote called myremote"
	echo "#        and name the branch mybranch."
	exit 0
}

if [ -z "$1" ]; then
	ge current_branch
	exit $?
fi


while [ ! -z "$1" ]
do
	case  "$1" in
		"--show-commands")
			shift
			show_commands=1
			;;
		"--help")
			print_usage
			exit 0
			;;
		"create")
			shift
			echo "Create branch"
			create_remote_branch "$1" "$2"
			;;
		"track")
			shift
			echo "Track branch"
			track_remote_branch "$1" "$2"
			;;
		"delete")
			shift
			echo "Delete branch"
			delete_remote_branch "$1" "$2"
			;;
		*)
			shift
			;;
	esac
done

exit 0
