#!/bin/bash

current_dir=`pwd`
base_dir=`dirname $0`

function get_current_branch() {
	git branch | grep '*' | sed 's/^\* \([a-zA-Z0-9]*\)/\1/'
}

function print_usage() {
	echo "gtk: Git Tool Kit"
	echo "Usage: gtk <command> [arguments]"
}

if [ -z "$1" ]
then
	print_usage
	exit 0
fi

case $1 in
	'current_branch')
		get_current_branch
		;;
	'ls')
		shift
		$base_dir/gtk-ls $@
		;;
	'review')
		shift
		$base_dir/gtk-review $@
		;;
	'help')
		shift
		$base_dir/gtk-$1 --help
		;;
esac

exit 0
